Enable the constraints checking for assembler by default if possible.
I get the request recently that the assembler's constraints checking break
hardware exception test cases.  Therefore I have disabled the checking in
assembler by default, and people don't get the constraints error when writing
assembly code.  But we should enable the checking for the code which the
compiler emits.

Beside, GCC also checks whether the assembler supports the options used to
enable and disable the constraints checking.  The basic logic is shown as
follows,

                  | GAS support              | GAS doesn't support
                  | constraints options      | constraints options
----------------------------------------------------------------------
 GCC default      | Output `.option          | Don't output the `.option
                  | checkconstraints`        | checkconstraints`
----------------------------------------------------------------------
 GCC `-mcheck-    | Output `.option          | Report error message that
 constraints`     | checkconstraints`        | GAS doesn't support `.option
                  |                          | checkconstraints`
----------------------------------------------------------------------
 GCC `-mno-check- | Don't output the`.option | Don't output the`.option
 constraints`     | checkconstraints`        | checkconstraints`

	gcc/
	* config.in: Regenerated.
	* configure: Likewise.
	* configure.ac: Check whether GAS support constraints .option directives.
	* config/riscv/riscv.c (riscv_option_override): If user don't set the
	`m[no-]check-constraints` option and GAS support the constraints
	checking, then GCC should enable it by default. If user set the
	`mcheck-constraints` options but the checking isn't supported in GAS,
	then we should report error message.
	(riscv_file_start): Emit `.option checkconstraints` if needed.
	* config/riscv/riscv.opt (mcheck-constraints): New option.

	gcc/testsuite/
	* gcc.target/riscv/constraints-1.c: New.
	* gcc.target/riscv/constraints-2.c: Likewise.

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -27635,6 +27635,41 @@ $as_echo "#define HAVE_AS_RISCV_ATTRIBUTE 1" >>confdefs.h
 
 fi
 
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for .option checkconstraints support" >&5
+$as_echo_n "checking assembler for .option checkconstraints support... " >&6; }
+if ${gcc_cv_as_riscv_check_constraints+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  gcc_cv_as_riscv_check_constraints=no
+    if test $in_tree_gas = yes; then
+    if test $gcc_cv_gas_vers -ge `expr \( \( 2 \* 1000 \) + 33 \) \* 1000 + 1`
+  then gcc_cv_as_riscv_check_constraints=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    $as_echo '.option checkconstraints' > conftest.s
+    if { ac_try='$gcc_cv_as $gcc_cv_as_flags --fatal-warnings -o conftest.o conftest.s >&5'
+  { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_try\""; } >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; }
+    then
+	gcc_cv_as_riscv_check_constraints=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $gcc_cv_as_riscv_check_constraints" >&5
+$as_echo "$gcc_cv_as_riscv_check_constraints" >&6; }
+if test $gcc_cv_as_riscv_check_constraints = yes; then
+
+$as_echo "#define HAVE_AS_RISCV_CHECK_CONSTRAINTS 1" >>confdefs.h
+
+fi
+
     ;;
     s390*-*-*)
     { $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for .gnu_attribute support" >&5
